cooperative_control:
  node_frequency: 10
  kc: 0.1
  Veh_ID: 0
  adj_matrix: [0, 1, 
              1, 0]
  # threshold function of ETC (for the CPF) is: g = c0 + c1e^(-c2*t)
  c0: 0.03
  c1: 0.02
  c2: 0.1

tracking_control:
  node_frequency: 10
  # gains of the tracking controller
  delta: -1
  kx: 0.4
  ky: 0.2
  kz: 0.4

dekf:
  node_frequency: 10
  Veh_ID: 0
  adj_matrix: [0, 1, 
              1, 0]
  state_offset: [4290797.543,  491941.239 , 0.0, 0.0] 
  ini_target_state: [ 10.0,   -5.0,    0.0,    0.0 ]
  ini_target_cov:   [ 10.0,   0.0,    0.0,    0.0, 
                      0.0,   10.0,    0.0,    0.0,
                      0.0,   0.0,    0.1,   0.0,
                      0.0,   0.0,    0.0,    0.1 ]
  target_depth: 1.5
  # threshold function of ETC (for the DEKF) is: g = c0 + c1e^(-c2*t)
  c0: 0
  c1: 0
  c2: 0

trajectory_planning:
  node_frequency: 10
  formation_offset: 90.0         # for Mblack vehicle, 90 for Mred
  radius_x: 10.0
  radius_y: 10.0
  radius_z: 0.0
  vd_bar: 0.03

range_simulation:
  node_frequency: 0.66

comms_client_slap:
  node_frequency: 10
  broadcast_port: 2809
#broadcast_address: "192.168.255.255"
  broadcast_address: "127.255.255.255"
  Veh_ID: 0

comms_server_slap:
  node_frequency: 10
  broadcast_port: 2809
#broadcast_address: "192.168.255.255"
  broadcast_address: "127.255.255.255"
  Veh_ID: 0